 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rejections", type: :request do
  # Rejection. As you add validations to Rejection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Rejection.create! valid_attributes
      get rejections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rejection = Rejection.create! valid_attributes
      get rejection_url(rejection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rejection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rejection = Rejection.create! valid_attributes
      get edit_rejection_url(rejection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Rejection" do
        expect {
          post rejections_url, params: { rejection: valid_attributes }
        }.to change(Rejection, :count).by(1)
      end

      it "redirects to the created rejection" do
        post rejections_url, params: { rejection: valid_attributes }
        expect(response).to redirect_to(rejection_url(Rejection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Rejection" do
        expect {
          post rejections_url, params: { rejection: invalid_attributes }
        }.to change(Rejection, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rejections_url, params: { rejection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rejection" do
        rejection = Rejection.create! valid_attributes
        patch rejection_url(rejection), params: { rejection: new_attributes }
        rejection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rejection" do
        rejection = Rejection.create! valid_attributes
        patch rejection_url(rejection), params: { rejection: new_attributes }
        rejection.reload
        expect(response).to redirect_to(rejection_url(rejection))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rejection = Rejection.create! valid_attributes
        patch rejection_url(rejection), params: { rejection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rejection" do
      rejection = Rejection.create! valid_attributes
      expect {
        delete rejection_url(rejection)
      }.to change(Rejection, :count).by(-1)
    end

    it "redirects to the rejections list" do
      rejection = Rejection.create! valid_attributes
      delete rejection_url(rejection)
      expect(response).to redirect_to(rejections_url)
    end
  end
end
