 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/session_assignments", type: :request do
  # SessionAssignment. As you add validations to SessionAssignment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SessionAssignment.create! valid_attributes
      get session_assignments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      session_assignment = SessionAssignment.create! valid_attributes
      get session_assignment_url(session_assignment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_session_assignment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      session_assignment = SessionAssignment.create! valid_attributes
      get edit_session_assignment_url(session_assignment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SessionAssignment" do
        expect {
          post session_assignments_url, params: { session_assignment: valid_attributes }
        }.to change(SessionAssignment, :count).by(1)
      end

      it "redirects to the created session_assignment" do
        post session_assignments_url, params: { session_assignment: valid_attributes }
        expect(response).to redirect_to(session_assignment_url(SessionAssignment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SessionAssignment" do
        expect {
          post session_assignments_url, params: { session_assignment: invalid_attributes }
        }.to change(SessionAssignment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post session_assignments_url, params: { session_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested session_assignment" do
        session_assignment = SessionAssignment.create! valid_attributes
        patch session_assignment_url(session_assignment), params: { session_assignment: new_attributes }
        session_assignment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the session_assignment" do
        session_assignment = SessionAssignment.create! valid_attributes
        patch session_assignment_url(session_assignment), params: { session_assignment: new_attributes }
        session_assignment.reload
        expect(response).to redirect_to(session_assignment_url(session_assignment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        session_assignment = SessionAssignment.create! valid_attributes
        patch session_assignment_url(session_assignment), params: { session_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested session_assignment" do
      session_assignment = SessionAssignment.create! valid_attributes
      expect {
        delete session_assignment_url(session_assignment)
      }.to change(SessionAssignment, :count).by(-1)
    end

    it "redirects to the session_assignments list" do
      session_assignment = SessionAssignment.create! valid_attributes
      delete session_assignment_url(session_assignment)
      expect(response).to redirect_to(session_assignments_url)
    end
  end
end
